config/routes.rb
Mexilist::Application.routes.draw do
  get "checkout" => 'checkout#index'
  post "checkout" => 'checkout#create'
  get "paquetes" => 'home#paquetes'

#  include 'lib/category_constraint.rb'
  get 'anuncios/update_cities', :as => 'update_cities', :to => 'anuncios#update_cities'
  get 'anuncios/update_category', :as => 'update_category', :to => 'anuncios#update_category'
  get 'anuncios/update_model', :as => 'update_model', :to => 'anuncios#update_model'

  get 'facebooks/index'
  get 'facebooks/login'
  get 'facebooks/logout'
  get 'facebooks/callback'
  get 'facebooks/menu'

  get '/auth/:provider' => 'authentications#blank'
  get '/auth/:provider/callback' => 'authentications#create'

  resources :anuncios do 
    collection do 
      get 'mis_anuncios'
      post 'contactar'
      post 'create_bot'
      get 'search'
      get 'renovar'
   end
  end
  resources :pictures

  get '/:state/:city/:category/anuncios/search' => 'anuncios#search', :constraints => CityCategoryConstraint
  get '/:state/:category/anuncios/search' => 'anuncios#search', :constraints => StateCategoryConstraint
  get '/:state/:city/anuncios/search' => 'anuncios#search', :constraints => CityConstraint
  get '/:state/anuncios/search' => 'anuncios#search', :constraints => StateConstraint
  get '/:category/anuncios/search' => 'anuncios#search', :constraints => CategoryConstraint


  get '/:state/:city/:category' => 'anuncios#index', :constraints => CityCategoryConstraint
  get '/:state/:category' => 'anuncios#index', :constraints => StateCategoryConstraint
  get '/:state/:city/:titulo/:id' => 'anuncios#show', :constraints => CityConstraint
  get '/:state/:city' => 'home#index', :constraints => CityConstraint
  get '/:state' => 'home#index', :constraints => StateConstraint
  get '/:category' => 'anuncios#index', :constraints => CategoryConstraint


  root :to => "home#index"
  devise_for :users
  resources :users do 
    member do 
      get 'anuncios'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_many :authentications, :dependent => :delete_all
  has_many :anuncios, :dependent => :delete_all
  has_many :votes
  has_many :pictures
  has_many :cards
  has_many :transactions

  def apply_omniauth(auth)
    # In previous omniauth, 'user_info' was used in place of 'raw_info'
    self.email =  auth['info']['email']
    # Again, saving token is optional. If you haven't created the column in authentications table, this will fail
    authentications.build(:provider => auth['provider'], :uid => auth['uid'], :token => auth['credentials']['token'])
  end

  def facebook

    if !self.authentications.empty?
      uid = self.authentications.first.uid
      FbGraph::User.fetch(uid) rescue nil
    else
      nil
    end
  end

  def fb_me
    if !self.authentications.empty?
      FbGraph::User.me(self.authentications.first.token) rescue nil
    end
  end


  def picture
    if facebook
      facebook.picture
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => :anuncios

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  def anuncios
    @user =  User.find(params[:id])
    @anuncios = @user.anuncios.order('fecha asc')
    if params[:anuncio_id]
      @anuncio = current_user.anuncios.find(params[:anuncio_id])
    end

  end
end

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline'
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/anuncios.html.haml
%h1
  %span.picture=image_tag(@user.picture)
  Anuncios de #{@user.name}
-if current_user == @user
  %h4
    Mexipuntos disponibles: #{current_user.mexipuntos}
    %small=link_to 'Adquiere más mexipuntos.', '/paquetes'

%ul#anuncio_list.list-group

  -@anuncios.each do |anuncio|
    %li.list-group-item
      =render 'anuncios/anuncio_list', :anuncio => anuncio, :renueva => true
      -if current_user == @user or (current_user and current_user.has_role? :admin) 
        .extra-info
          %span=link_to 'autorenovar', renovar_anuncios_url(:id => anuncio.id), :remote => true
          %span=link_to 'editar', edit_anuncio_url(anuncio)
          %span=link_to 'borrar', anuncio, :method => :delete, :confirm => "Estas seguro?"
          %span="visitas: " + anuncio.impressionist_count.to_s

#autorenueva.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title Autorenueva

      .modal-body
        =render 'anuncios/renovar', :anuncio => @anuncio if @anuncio
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Cerrar
        %button.btn.btn-primary{type: "button", :onclick => "$('#autorenueva form').submit();"} Guardar
      .modal-content
    .modal-dialog
  .modal
-if @anuncio
  :javascript
    $('#autorenueva').modal('show');

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}