config/routes.rb
Mexilist::Application.routes.draw do
  get "checkout" => 'checkout#index'
  post "checkout" => 'checkout#create'
  get "paquetes" => 'home#paquetes'

#  include 'lib/category_constraint.rb'
  get 'anuncios/update_cities', :as => 'update_cities', :to => 'anuncios#update_cities'
  get 'anuncios/update_category', :as => 'update_category', :to => 'anuncios#update_category'
  get 'anuncios/update_model', :as => 'update_model', :to => 'anuncios#update_model'

  get 'facebooks/index'
  get 'facebooks/login'
  get 'facebooks/logout'
  get 'facebooks/callback'
  get 'facebooks/menu'

  get '/auth/:provider' => 'authentications#blank'
  get '/auth/:provider/callback' => 'authentications#create'

  resources :anuncios do 
    collection do 
      get 'mis_anuncios'
      post 'contactar'
      post 'create_bot'
      get 'search'
      get 'renovar'
   end
  end
  resources :pictures

  get '/:state/:city/:category/anuncios/search' => 'anuncios#search', :constraints => CityCategoryConstraint
  get '/:state/:category/anuncios/search' => 'anuncios#search', :constraints => StateCategoryConstraint
  get '/:state/:city/anuncios/search' => 'anuncios#search', :constraints => CityConstraint
  get '/:state/anuncios/search' => 'anuncios#search', :constraints => StateConstraint
  get '/:category/anuncios/search' => 'anuncios#search', :constraints => CategoryConstraint


  get '/:state/:city/:category' => 'anuncios#index', :constraints => CityCategoryConstraint
  get '/:state/:category' => 'anuncios#index', :constraints => StateCategoryConstraint
  get '/:state/:city/:titulo/:id' => 'anuncios#show', :constraints => CityConstraint
  get '/:state/:city' => 'home#index', :constraints => CityConstraint
  get '/:state' => 'home#index', :constraints => StateConstraint
  get '/:category' => 'anuncios#index', :constraints => CategoryConstraint


  root :to => "home#index"
  devise_for :users
  resources :users do 
    member do 
      get 'anuncios'
    end
  end

end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
  attr_accessible :category_id, :city_id, :district, :expiracy, :latitude, :longitude, :price, :renovation, :street, :texto, :tipo, :title, :assets_attributes, :tel, :car_perk_attributes, :moto_perk_attributes, :house_perk_attributes, :token, :intercambio, :job_perk_attributes, :frecuencia, :noches, :bot_id
  has_many :assets
  belongs_to :city
  belongs_to :state
  belongs_to :category
  belongs_to :user
  has_one :car_perk
  has_one :moto_perk
  has_one :house_perk
  has_one :job_perk
  has_many :pictures,  :dependent => :destroy
  is_impressionable

  accepts_nested_attributes_for :assets, :reject_if => lambda { |a| a[:file].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :car_perk, :allow_destroy => true
  accepts_nested_attributes_for :moto_perk, :allow_destroy => true
  accepts_nested_attributes_for :house_perk, :allow_destroy => true
  accepts_nested_attributes_for :job_perk, :allow_destroy => true

  
  TIPOS = [['Venta', 1], ['Compra', 2], ['Renta', 3], ['Servicios', 4], ['Ofresco Trabajo', 5], ['Busco Trabajo', 6]]

  validates :category_id, :presence => true
  validates :city_id, :presence => true
  validates :tipo, :presence => true
  validates :title, :presence => true
  validates :texto, :presence => true



  scope :with_picture, -> { joins(:pictures).uniq }
 
  scope :by_location_with_picture, ->(state, city){ 

    if city
      Anuncio.where(:city_id =>  City.find_name(city).id).joins(:pictures).uniq 
    elsif state
      Anuncio.where(:state_id => State.find_name(state).id).joins(:pictures).uniq 
    else
      Anuncio.joins(:pictures).uniq 
    end

  }
  
  scope :by_category, ->(category){ 
    ids = [category.id]
    category.subcategories.each{|sub| ids << sub.id}
    Anuncio.joins(:city, :category).where("categories.id in (?)", ids) }

  scope :by_city_category, ->(city, category){ 
    ids = [category.id]
    category.subcategories.each{|sub| ids << sub.id}
    Anuncio.joins(:city, :category).where("cities.id = ? and categories.id in (?)", city, ids) }
  scope :by_state_category, ->(state, category){ 
    ids = [category.id]
    category.subcategories.each{|sub| ids << sub.id}
    Anuncio.joins(:state, :category).where("states.id = ? and categories.id in (?)", state, ids) }


  def main_image(size=nil)
    if size == :original
    if !self.pictures.empty?
      self.pictures.first.image.url
    else
      "http://placehold.it/246x180"
    end

    else
    if !self.pictures.empty?
      self.pictures.first.image.thumb.url
    else
      "http://placehold.it/160x120"
    end
    end
  end

#  TIPOS = [['Venta', 1], ['Compra', 2], ['Renta', 3], ['Servicios', 4], ['Ofresco Trabajo', 5], ['Busco Trabajo', 6]] 

  def tipo_name
    if tipo == 1 
      'Venta'
    elsif tipo == 2
      'Compra'
    elsif tipo == 3
      'Renta'
    elsif tipo == 4
      'Servicios'
    elsif tipo == 5
      'Ofresco Trabajo'
    elsif tipo == 6
      'Busco Trabajo'
    end
  end

  def build_perk
    if self.category.car?
      self.build_car_perk
    elsif self.category.moto?
      self.build_moto_perk
    elsif self.category.house?
      self.build_house_perk
    end
  end

  def main_category
    self.category.parent
  end

  def main_category_name
    self.category.parent.name
  end


  def category_name
    self.category.name
  end

  def render_name    
    if self.category.car?
      'car'
    elsif self.category.moto?
      'moto'
    elsif self.category.house?
      'house'
    elsif self.category.job?
      'job'
    else
      return 'normal'
    end

  end

  def tipo_asdf
    if self.category.tipo
      self.category.tipo
    else
      self.category.parent.tipo
    end
  end


  def url
    "http://mexilist.com/" + self.state.name.parameterize + "/" + self.city.name.parameterize + "/" + self.title.parameterize + "/" + self.id.to_s
  end
  
end

app/controllers/anuncios_controller.rb
# -*- coding: utf-8 -*-


require 'twitter-text'
include Twitter::Autolink

class AnunciosController < ApplicationController
  load_and_authorize_resource :except => [:contactar, :create_bot]
  require 'will_paginate/array'
  def create_bot
    if (params[:anuncio][:title] =~ /Tu Tienda en Anumex/).nil?

      user = User.find_or_create_by(email: params[:user][:email])
      user.name = params[:user][:name]
      user.password = params[:user][:email]
      user.save

      anuncio = Anuncio.find_or_create_by(bot_id: params[:anuncio][:bot_id])
      anuncio.title = params[:anuncio][:title].gsub(/anumex/i, 'mexilist')

      anuncio.tipo = params[:anuncio][:tipo]
      anuncio.price = params[:anuncio][:price].gsub(',', '')
      anuncio.texto = params[:anuncio][:texto].gsub(/anumex/i, 'mexilist')
      anuncio.tel = params[:anuncio][:tel]
      anuncio.user_id = user.id

      anuncio.fecha = params[:anuncio][:fecha]
      anuncio.category_id = CategoryMapper.find_by_anumex_id(params[:anuncio][:category]).category_id

      if params[:anuncio][:model_id]
        model = Model.find(params[:anuncio][:model_id])
        anuncio.build_car_perk(:brand_id => model.brand_id, :model_id => params[:anuncio][:model_id], :year => params[:anuncio][:year], :km => params[:anuncio][:km])
      end

      if params[:anuncio][:cc]
        brand = Brand.find(params[:anuncio][:brand_id])
        anuncio.build_moto_perk(:brand_id => brand.id, :year => params[:anuncio][:year], :km => params[:anuncio][:km], :cc => params[:anuncio][:cc])

      end
      if params[:anuncio][:rooms]
        anuncio.build_house_perk(:colonia => params[:anuncio][:colonia] ,:rooms => params[:anuncio][:rooms], :m2int => params[:anuncio][:m2int], :m2ext => params[:anuncio][:m2ext])
        anuncio.latitude = params[:anuncio][:latitude]
        anuncio.longitude = params[:anuncio][:longitude]
        anuncio.district = params[:anuncio][:district]
      end


      city = CityMapper.find_by_anumex_id(params[:anuncio][:city]).city rescue city = nil
      if city
        anuncio.city_id = city.id
        anuncio.state_id = city.state_id
      end



      if anuncio.save
        if anuncio.fecha > Date.today
          anuncio.update_attribute(:fecha, Date.today)
        end

        params[:anuncio][:images].each_pair do |key, value|
          file = File.open(key.gsub('/pictures/', './tmp/images/'), 'wb') {|file| file << (value.unpack('m')).first }
          pic = Picture.find_or_create_by(image: File.basename(file.path))
          pic.image = File.new(file)
          pic.user_id = user.id
          pic.anuncio_id = anuncio.id
          pic.save
        end

      end


    end
#    render :json => {:status => 200}.to_json, :status => 200
    render :partial => 'anuncio.html.haml', :locals => {:anuncio => anuncio}
  end

  def update_model

    brand = Brand.find(params[:brand_id])
    # map to name and id for use in our options_for_select
    @models = brand.models.map{|a| [a.name, a.id]}
    respond_to do |format|
      format.js
    end
  end
  def update_cities
    # updates artists and songs based on genre selected
    state = State.find(params[:state_id])
    # map to name and id for use in our options_for_select
    @cities = state.cities.map{|a| [a.name, a.id]}
    respond_to do |format|
      format.js
    end
  end

  def update_category
    # updates artists and songs based on genre selected
    category = Category.find(params[:category_id])
    # map to name and id for use in our options_for_select
    @anuncio = current_user.anuncios.build(:category_id => category.id)

    5.times { @anuncio.assets.build }
    @anuncio.build_perk


    respond_to do |format|
      format.js
    end
  end


  # GET /anuncios
  # GET /anuncios.json
  def index

    if params[:city] and params[:category]
      @city = nil
      City.all.each{|city| @city = city if city.param_name == params[:city]}
      @category = nil
      Category.all.each{|cat| @category = cat if cat.url_name == params[:category]}
      @anuncios = Anuncio.by_city_category(@city.id, @category).order('fecha desc')
      @title = @category.keywords

    elsif params[:state] and params[:category]
      @state = nil
      State.all.each{|state| @state = state if state.param_name == params[:state]}
      @category = nil
      Category.all.each{|cat| @category = cat if cat.url_name == params[:category]}
      @anuncios = Anuncio.by_state_category(@state.id, @category).order('fecha desc')
      @title = @category.keywords
    elsif params[:category]
      @category = nil
      Category.all.each{|cat| @category = cat if cat.url_name == params[:category]}
      @anuncios = Anuncio.by_category(@category).order('fecha desc')
      @title = @category.keywords
    else
      @anuncios = Anuncio.all.order('fecha desc')
      @title = "Mexilist.com"
    end

    if params[:anuncio_id]
      @anuncio = Anuncio.find(params[:anuncio_id])
    end

    @anuncios_auto = @anuncios.where('frecuencia IS NOT NULL')
    @todos = (@anuncios_auto + @anuncios).uniq.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @anuncios }
    end
  end

  def mis_anuncios
    @anuncios = current_user.anuncios
  end

  # GET /anuncios/1
  # GET /anuncios/1.json
  def show
    @anuncio = Anuncio.find(params[:id])

    @related = Anuncio.where(:category_id => @anuncio.category_id).last(4)
    @related = Anuncio.last(5)
    impressionist(@anuncio)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @anuncio }
    end
  end

  # GET /anuncios/new
  # GET /anuncios/new.json
  def new

    @sub = params[:sub]
    @last_anuncio = current_user.anuncios.last
    @anuncio = current_user.anuncios.build

    @picture = Picture.new
    if params[:token]
      @token = params[:token]
    else
      @token = (DateTime.now.to_i + current_user.id).to_s
    end

    if @sub
      @anuncio.category = Category.find(@sub) rescue nil
      @images = Picture.find_all_by_token(@token)
    end


    @anuncio.build_car_perk
    @anuncio.build_house_perk
    @anuncio.build_moto_perk
    @anuncio.build_job_perk

    @states = State.all
    @cities = City.all
    5.times { @anuncio.assets.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @anuncio }
    end
  end

  # GET /anuncios/1/edit
  def edit
    if current_user.has_role? :admin
      @anuncio = Anuncio.find(params[:id])
    else
      @anuncio = current_user.anuncios.find(params[:id])
    end
    @picture = Picture.new
    @images = @anuncio.pictures


    @states = State.all
    @cities = City.all

  end

  # POST /anuncios
  # POST /anuncios.json
  def create
    @anuncio = current_user.anuncios.build(params[:anuncio])

    @anuncio.state_id = City.find(params[:anuncio][:city_id]).state.id
    @images = Picture.find_all_by_token(@anuncio.token)


    respond_to do |format|
      if @anuncio.save
        @images.each do |pic|
          pic.update_attribute(:anuncio_id, @anuncio.id)
        end
        @anuncio.update_attribute(:fecha, @anuncio.created_at)
        if current_user.anuncios.count == 1
          current_user.update_attribute(:mexipuntos, current_user.mexipuntos + 25)
        end
        current_user.fb_me.link!(:link => @anuncio.url,:message => @anuncio.title + " #mexilist")
        format.html { redirect_to anuncios_user_url(current_user, :anuncio_id => @anuncio.id), notice: 'Anuncio creado exitosamente.' }
        format.json { render json: @anuncio, status: :created, location: @anuncio }
      else
        @sub = @anuncio.category_id
        @states = State.all
        @cities = City.all
        @picture = Picture.new

        format.html {  render :action => 'new', :token => @anuncio.token }

        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /anuncios/1
  # PUT /anuncios/1.json
  def update
    if current_user.has_role? :admin
      @anuncio = Anuncio.find(params[:id])
    else
      @anuncio = current_user.anuncios.find(params[:id])
    end
    @anuncio.state_id = City.find(params[:anuncio][:city_id]).state.id if params[:anuncio][:city_id]
    respond_to do |format|
      if @anuncio.update_attributes(params[:anuncio])
        format.html { redirect_to @anuncio, notice: 'Anuncio actualizado exitosamente.' }
        format.json { head :no_content }
        format.js { render :js => "$('#autorenueva').modal('hide');" }
      else
        format.html { render action: "edit" }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  def contactar

    @anuncio = Anuncio.find params[:anuncio_id]
    if @anuncio
      AnuncioMailer.contactar(params[:email], params[:nombre], params[:mensaje], @anuncio).deliver
    end

    respond_to do |format|
      format.js { render :js => "$('.enviar').show(); $('.enviar_dis').hide(); $('.modal').modal('hide'); alert('Tu mensaje fue enviado con exito.');"}
    end
  end

  # DELETE /anuncios/1
  # DELETE /anuncios/1.json
  def destroy
    if current_user.has_role? :admin
      @anuncio = Anuncio.find(params[:id])
    else
      @anuncio = current_user.anuncios.find(params[:id])
    end
    @anuncio.destroy

    respond_to do |format|
      format.html { redirect_to mis_anuncios_anuncios_url }
      format.json { head :no_content }
    end
  end


  def search


    with_hash = { }
    if params[:city].nil? and params[:state]
      @state = nil
      State.all.each{|state| @state = state if state.param_name == params[:state]}
      with_hash = { :state_id => @state.id }
    elsif params[:city]
      @city = nil
      City.all.each{|city| @city = city if city.param_name == params[:city]}
      with_hash = { :city_id => @city.id }
    end
    if params[:category]
      @cat = nil

app/helpers/anuncios_helper.rb
module AnunciosHelper

  def city_anuncio_url(anuncio)
    anuncio.city.url_name + "/" + anuncio.title.parameterize + "/" + anuncio.id.to_s
  end


  def category_list(num)
    parent=Category.find(num)
    capture_haml do
      haml_tag(:div, :class => 'category_list well') do
        haml_tag(:strong, parent.name)
        haml_concat image_tag('icons/'+parent.name.parameterize+'.png')
        haml_tag(:ul) do 
          parent.subcategories.each do |sub|
            haml_tag(:li) do 
              haml_concat link_to(sub.name, new_anuncio_url+"?sub="+sub.id.to_s+"&token="+@token)
            end
          end
        end
      end
    end

  end

end

app/views/anuncios/_car.html.haml
=simple_fields_for @anuncio do |f|
  =f.input :district, :label => 'Colonia', input_html: {:value => @last_anuncio.nil? ? '' : @last_anuncio.district}


  %fieldset.perk.controls-row
    %legend Caracteristicas del Vehículo
    =f.simple_fields_for :car_perk do |asset_form|
      .col-sm-3
        =asset_form.input :brand_id, :collection => Brand.all
      .col-sm-3
        =asset_form.input :model_id, :collection => Model.all
      .col-sm-3
        =asset_form.input :km
      .col-sm-3
        =asset_form.input :year, :collection => 1950..(Time.now.year + 1)

    =f.input :price, :label => 'Precio'

  =render 'anuncio_basic', :f => f

:javascript
  $('#anuncio_car_perk_attributes_brand_id').change(function() {
    $.ajax({
      url: "#{update_model_path}",
      data: {
        brand_id : $('#anuncio_car_perk_attributes_brand_id').val()
      },
      dataType: "script"
    });
  });

app/views/anuncios/_house.html.haml
=simple_fields_for @anuncio do |f|
  .perk.controls-row
    =f.input :district, :label => 'Colonia', input_html: {:value => @last_anuncio.nil? ? '' : @last_anuncio.district}
    =f.input :street, :label => 'Calle y número'
    =f.input :latitude, :as => :hidden
    =f.input :longitude, :as => :hidden

  %fieldset.perk.controls-row
    %legend Características
    =f.simple_fields_for :house_perk do |asset_form|
      .col-sm-4
        =asset_form.input :rooms, :label => 'Cuartos', :collection => 1..10
      .col-sm-4
        =asset_form.input :m2int, :label => "Metros Interior"
      .col-sm-4
        =asset_form.input :m2ext, :label => "Metros Exterior"

    =f.input :price, :label => 'Precio', input_html: { class: 'span2'}



  =render 'anuncio_basic', :f => f

app/views/anuncios/_moto.html.haml
=simple_fields_for @anuncio do |f|
  =f.input :district, :label => 'Colonia', input_html: {:value => @last_anuncio.nil? ? '' : @last_anuncio.district}

  %fieldset.perk.controls-row
    %legend Características de la Moto
    =f.simple_fields_for :moto_perk do |asset_form|
      .col-sm-3
        =asset_form.input :brand_id, :collection => Brand.all
      .col-sm-3
        =asset_form.input :km
      .col-sm-3
        =asset_form.input :cc
      .col-sm-3
        =asset_form.input :year, :collection => 1950..(Time.now.year + 1)

  =render 'anuncio_basic', :f => f

app/views/anuncios/_normal.html.haml
=simple_fields_for @anuncio do |f|
  =f.input :district, :label => 'Colonia', input_html: {:value => @last_anuncio.nil? ? '' : @last_anuncio.district}

  =f.input :price, :label => 'Precio', input_html: { class: 'span2'}

  =render 'anuncio_basic', :f => f

app/views/anuncios/_show_house.html.haml
%ul.col-md-4
  -if !@anuncio.price.blank?
    %li.well.precio.well-sm
      %span=number_to_currency(@anuncio.price)
  -if !@anuncio.district.blank?
    %li.well.well-sm
      %h3 colonia
      %span=@anuncio.district

%ul.col-md-4
  -if !@anuncio.house_perk.rooms.blank?
    %li.well.well-sm
      %h3 cuartos
      %span=@anuncio.house_perk.rooms
  -if !@anuncio.house_perk.m2int.blank?
    %li.well.well-sm
      %h3 m2 interior
      %span=number_with_precision(@anuncio.house_perk.m2int, precision: 0, delimiter: ',')
  -if !@anuncio.house_perk.m2ext.blank?
    %li.well.well-sm
      %h3 m2 exterior
      %span=number_with_precision(@anuncio.house_perk.m2ext, precision: 0, delimiter: ',')

app/views/anuncios/_show_job.html.haml
%ul.col-md-4
  -if !@anuncio.price.blank?
    %li.well.well-sm
      %h3 sueldo
      %span=number_to_currency(@anuncio.price)
  -if !@anuncio.job_perk.cv_url.blank?
    %li.well.well-sm
      %h3 cv
      %span=link_to("Ver currículo", @anuncio.job_perk.cv_url)

%ul.col-md-4
  -if !@anuncio.job_perk.estudios.blank?
    %li.well.job.well-sm
      %h3 estudios
      %span=@anuncio.job_perk.estudios
  -if !@anuncio.job_perk.area.blank?
    %li.well.job.well-sm
      %h3 area
      %span=@anuncio.job_perk.area

app/views/anuncios/_show_moto.html.haml
%ul.col-md-4
  -if !@anuncio.price.blank?
    %li.well.precio.well-sm
      %span=number_to_currency(@anuncio.price)
  -if !@anuncio.moto_perk.km.blank?
    %li.well.well-sm
      %h3 km
      %span=number_with_precision(@anuncio.moto_perk.km, precision: 0, delimiter: ',')
  -if !@anuncio.moto_perk.cc.blank?
    %li.well.well-sm
      %h3 cc
      %span=@anuncio.moto_perk.cc

%ul.col-md-4
  -if !@anuncio.moto_perk.brand.nil?
    %li.well.well-sm
      %h3 marca
      %span=@anuncio.moto_perk.brand.name
  -if !@anuncio.moto_perk.year.blank?
    %li.well.well-sm
      %h3 año
      %span=@anuncio.moto_perk.year

app/views/anuncios/edit.html.haml
%h1 Editar anuncio

= render 'form'

app/views/anuncios/index.html.haml
=content_for :title do
  =@title.titlecase

-content_for :breadcrumb do
  .breadcrumb
    %li
      =link_to('Inicio', root_url)
    -if @city
      %li
        =link_to(@city.name,  @city.url_name)
    -if @category and @category.parent
      %li
        =link_to(@category.parent.name, @category.parent.name.parameterize )

    -if @category
      %li.active
        =@category.keywords.titlecase


.col-sm-12
  -if !params[:city].blank?
    %h1=(@category.blank? ? "Anuncios" : @category.name) + " en " + params[:city].titlecase
  -elsif !params[:state].blank?
    %h1=(@category.blank? ? "Anuncios" : @category.name) + " en " + params[:state].titlecase
  -else
    %h1= @category.blank? ? "Anuncios" : @category.name
  %span.text-muted Encontrados <strong>#{@todos.total_entries}</strong> anuncios
  -if @category.blank? and action_name != "search"
    #anuncios_container

      -@todos.each do |anuncio|
        =render anuncio
    =will_paginate @todos, :container => 'li'
  -else
    %ul#anuncio_list.list-group
      -@todos.each do |anuncio|
        %li.list-group-item{:itemscope => true,  :itemtype => "http://schema.org/Product" }=render 'anuncio_list', :anuncio => anuncio
    =will_paginate @todos

app/views/anuncios/new.html.haml
-content_for :head do 
  :javascript
    $().ready(function() {
    $(".green_light").validate({"rules":{"anuncio[category_id]":{"required":true},"anuncio[city_id]":{"required":true},"anuncio[tipo]":{"required":true},"anuncio[title]":{"required":true},"anuncio[texto]":{"required":true},"anuncio[Estado]":{},"anuncio[district]":{},"anuncio[price]":{},"anuncio[tel]":{}},"errorElement":"span"});
    });
    $.validator.addMethod(
    "regex",
    function(value, element, regexp) {
    var check = false;
    var re = new RegExp(regexp);
    return this.optional(element) || re.test(value);
    },
    "You have entered an invalid value for this field"
    );



-if @sub.nil?
  .col-sm-12
    %h1 Crea tu anuncio
  .select_cat.col-sm-12
    %h3 1. Selecciona una categoría

    .row

      .col-sm-3
        =category_list(10)
        =category_list(300)

      .col-sm-3
        =category_list(500)
        =category_list(400)

      .col-sm-3
        =category_list(200)
        =category_list(600)

      .col-sm-3
        =category_list(100)



  .clearfix

-else
  =render 'form'

app/views/anuncios/update.js.haml
$('#cities_select').html("#{escape_javascript(options_for_select(@cities))}");

app/views/anuncios/update_model.js.haml
$("#anuncio_car_perk_attributes_model_id").html("#{escape_javascript(options_for_select(@models))}");