config/routes.rb
Mexilist::Application.routes.draw do
  get "checkout" => 'checkout#index'
  post "checkout" => 'checkout#create'
  get "paquetes" => 'home#paquetes'

#  include 'lib/category_constraint.rb'
  get 'anuncios/update_cities', :as => 'update_cities', :to => 'anuncios#update_cities'
  get 'anuncios/update_category', :as => 'update_category', :to => 'anuncios#update_category'
  get 'anuncios/update_model', :as => 'update_model', :to => 'anuncios#update_model'

  get 'facebooks/index'
  get 'facebooks/login'
  get 'facebooks/logout'
  get 'facebooks/callback'
  get 'facebooks/menu'

  get '/auth/:provider' => 'authentications#blank'
  get '/auth/:provider/callback' => 'authentications#create'

  resources :anuncios do 
    collection do 
      get 'mis_anuncios'
      post 'contactar'
      post 'create_bot'
      get 'search'
      get 'renovar'
   end
  end
  resources :pictures

  get '/:state/:city/:category/anuncios/search' => 'anuncios#search', :constraints => CityCategoryConstraint
  get '/:state/:category/anuncios/search' => 'anuncios#search', :constraints => StateCategoryConstraint
  get '/:state/:city/anuncios/search' => 'anuncios#search', :constraints => CityConstraint
  get '/:state/anuncios/search' => 'anuncios#search', :constraints => StateConstraint
  get '/:category/anuncios/search' => 'anuncios#search', :constraints => CategoryConstraint


  get '/:state/:city/:category' => 'anuncios#index', :constraints => CityCategoryConstraint
  get '/:state/:category' => 'anuncios#index', :constraints => StateCategoryConstraint
  get '/:state/:city/:titulo/:id' => 'anuncios#show', :constraints => CityConstraint
  get '/:state/:city' => 'home#index', :constraints => CityConstraint
  get '/:state' => 'home#index', :constraints => StateConstraint
  get '/:category' => 'anuncios#index', :constraints => CategoryConstraint


  root :to => "home#index"
  devise_for :users
  resources :users do 
    member do 
      get 'anuncios'
    end
  end

end

app/views/layouts/_left_menu.html.haml
-city = params[:city].blank? ? '' : params[:city] + "/"
-state = params[:state].blank? ? '' : params[:state] + "/"
#category_menu
  .dropdown.clearfix
    %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu", :role => "menu"}
      -Category.main_categories.each do |mcat|
        -if mcat.has_children?
          %li.dropdown-submenu
            %a{:href => root_url + state + city + mcat.url_name, :tabindex => "-1"}
              %i=image_tag('icons/' + mcat.name.parameterize + '.png')
              =mcat.name
            %ul.dropdown-menu
              -mcat.subcategories.each do |sub|
                %li
                  %a{:href => root_url + state + city + sub.url_name, :tabindex => "-1"}=sub.name
        -else
          %li
            %a{:href => root_url + state + city +  mcat.url_name, :tabindex => "-1"}=mcat.name

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "flash-alert alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-city = params[:city].blank? ? '' : params[:city] + "/"
-state = params[:state].blank? ? '' : params[:state] + "/"
-category = params[:category].blank? ? '' : params[:category] + "/"

.navbar-header
  %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", :type => "button"}
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
  =link_to image_tag('mexilist.png'), root_path, :class => 'navbar-brand'

.linea
.nav.navbar-nav.col-sm-7{:role => "search"}
  -cache('categorias-'+ params[:city].to_s + '-' + params[:state].to_s) do
    .hidden-xs.col-sm-3
      #busca_por_categoria
        Busca por
        %strong categoría
        =render 'layouts/left_menu'

  .form-group.col-sm-9
    .row
      %form.col-sm-12{:action => root_url + state + city + category + 'anuncios/search', :method => 'get'}
        .input-group
          .input-group-btn
            .btn.btn-default.city_states_btn
              -if !params[:city].blank?
                =City.find_name(params[:city]).name
              -elsif !params[:state].blank?
                =State.find_name(params[:state]).name
              -else
                Todo Mexico
              %span.caret
          -cache('ciudades') do
            #city_states
              .states
                -State.all.each do |state|
                  .state{:onclick => "$('#cities" + state.id.to_s + "').show();$('.states').hide()"}=state.name
              -State.all.each do |state|
                %div.cities{:id => 'cities'+state.id.to_s}
                  %h4
                    =link_to(state.name, state.url_name)
                    =link_to('atras', '#', :onclick => "$('#cities" + state.id.to_s + "').hide();$('.states').show()", :class => 'atras' )
                  -state.cities.each do |c|
                    =link_to c.name, c.url_name, :class => 'city'

          %input#search.form-control{:type => "text", :name => 'q', :value => params[:q]}/
          %span.input-group-btn
            %button.btn.btn-default{:type => "submit"} Buscar

-if user_signed_in?
  %ul.navbar-nav.navbar-right.col-sm-4
    %li.publicar_btn
      =button_to('Publicar Anuncio', new_anuncio_url, :class => 'btn btn-danger', :method => :get)
    %li
      .btn-group
        %button.btn.btn-default{:type => "button"}
          %span.picture=image_tag(current_user.picture)
          =current_user.name
        %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
          %span.caret
        %ul.dropdown-menu
          %li=link_to "Mis Anuncios", anuncios_user_url(current_user)
          %li=link_to "Editar Cuenta", edit_user_registration_path
          %li.divider
          %li=link_to 'Salir', destroy_user_session_path, :method=>'delete'

    -#%li=button_to('Mis Anuncios', mis_anuncios_anuncios_path, :class => 'btn btn-primary', :method => :get )


-else
  %ul.navbar-nav.navbar-right
    %li.pull-right
      %button.publicar_btn.btn.btn-danger{:type=>'button', :onclick => "$('#login_modal').modal('show');"}Publicar Anuncio
    %li.btn.btn-default.pull-right=link_to 'Ingresar', '#', :onclick => "$('#login_modal').modal('show');"

app/views/layouts/_navigation_mobile.html.haml
-city = params[:city].blank? ? '' : params[:city] + "/"
-state = params[:state].blank? ? '' : params[:state] + "/"
-category = params[:category].blank? ? '' : params[:category] + "/"

.navbar-header
  %button.navbar-toggle.search_btn{"data-target" => "#search_toggle", "data-toggle" => "collapse", :type => "button"}
    %span.sr-only Toggle navigation
    %span.glyphicon.glyphicon-search
  %button.navbar-toggle.location_btn{"data-target" => "#location_toggle", "data-toggle" => "collapse", :type => "button"}
    %span.sr-only Toggle navigation
    %span.glyphicon.glyphicon-globe

  =link_to image_tag('mexilist.png'), root_path, :class => 'navbar-brand'
  %button.navbar-toggle.account_btn{"data-target" => "#account_toggle", "data-toggle" => "collapse", :type => "button"}
    %span.sr-only Toggle navigation
    %span.glyphicon.glyphicon-user

#search_toggle.collapse.navbar-collapse
  #search_mobile
    %form{:action => root_url + state + city + category + 'anuncios/search', :method => 'get'}
      .col-xs-9
        %input#search.form-control{:type => "text", :name => 'q', :value => params[:q]}/
      .col-xs-3
        %span.input-group-btn
          %button.btn.btn-default{:type => "submit"} Buscar

  %ul
    -Category.main_categories.each do |mcat|
      -if mcat.has_children?
        %li.main_cat{:onclick => "$('."+mcat.name.parameterize+"_sub').toggle();"}
          %i=image_tag('icons/' + mcat.name.parameterize + '.png')
          =mcat.name
        %a{:href =>  root_url + state + city + mcat.url_name}
          %li.sub_cat{:class => mcat.name.parameterize + "_sub"}
            ="Todo en " + mcat.name
        -mcat.subcategories.each do |sub|
          %a{:href => root_url + state + city + sub.url_name}
            %li.sub_cat{:class => mcat.name.parameterize + "_sub"}
              =sub.name
      -else
        %li.main_cat
          %a{:href => root_url + state + city +  mcat.url_name}=mcat.name

#location_toggle.collapse.navbar-collapse
  Aqui van las ciudades

#account_toggle.collapse.navbar-collapse
  -if user_signed_in?
    %ul.navbar-nav
      %li=button_to('Publicar Anuncio', new_anuncio_url, :class => 'btn btn-danger col-xs-12', :method => :get)
      %li=button_to("Mis Anuncios", anuncios_user_url(current_user), :class => 'btn btn-default col-xs-12', :method => :get)
      %li=button_to("Editar Cuenta", edit_user_registration_path, :class => 'btn btn-default col-xs-12', :method => :get)
      %li=button_to('Salir', destroy_user_session_path, :class => 'btn btn-default col-xs-12', :method => :delete)



  -else
    %ul.navbar-nav
      %li
        %button.btn.btn-danger.col-xs-12{:type=>'button', :onclick => "$('#login_modal').modal('show');"}Publicar Anuncio
      %li.btn.btn-default.col-xs-12=link_to 'Ingresar', '#', :onclick => "$('#login_modal').modal('show');"

app/views/layouts/application.html.haml
-city = params[:city].blank? ? '' : params[:city] + "/"
-state = params[:state].blank? ? '' : params[:state] + "/"
-category = params[:category].blank? ? '' : params[:category] + "/"

!!!
%html{:prefix=>"og: http://ogp.me/ns#"}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Mexilist"
    %meta{:content => content_for(:description) ? yield(:description) : "Red social de anuncios clasificados gratuitos en México. Encuentra vehículos, tecnología, inmuebles, hogar, recreación, personal y mucho más.", :name => "description"}
    :javascript
      var CKEDITOR_BASEPATH = '/ckeditor/';
    =stylesheet_link_tag "application", :media => "all"
    =javascript_include_tag "application"
    <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
    <link "https://plus.google.com/102065028150788699450"  rel="publisher"/>
    =csrf_meta_tags
    =yield(:head)

    <meta property="fb:app_id" content="124337484410517" />

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-45017816-1', 'mexilist.com');
      ga('send', 'pageview');



  %body{:class => "#{controller_name} #{action_name}"}
    #fb-root
    :javascript
      window.fbAsyncInit = function() {
      FB.init({
      appId : "#{ENV['facebook_app_id']}",
      status : true, // check login status
      oauth      : true,
      cookie : true, // enable cookies to allow the server to access the session
      xfbml : true // parse XFBML
      });
      };
      (function(d) {
      var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
      js = d.createElement('script'); js.id = id; js.async = true;
      js.src = "//connect.facebook.net/en_US/all.js";
      d.getElementsByTagName('head')[0].appendChild(js);
      }(document));


    %header
      %nav.navbar.navbar-default.hidden-xs{:role => "navigation"}
        =render 'layouts/navigation'
      %nav.navbar.navbar-default.visible-xs.mobile_menu{:role => "navigation"}
        =render 'layouts/navigation_mobile'




    #main{:role => "main"}
      -cache('estados') do
        #left_banner.hidden-xs
          #estados
            %h4 Estados
            %ul
              -State.all.each do |metro|
                %li=link_to(metro.name, metro.url_name)

      #right_banner.hidden-xs
        :javascript
          <!--
          google_ad_client = "ca-pub-9284427016001944";
          /* mexilist */
          google_ad_slot = "5065937288";
          google_ad_width = 120;
          google_ad_height = 600;
          //-->

        %script{:type => "text/javascript", :src => "http://pagead2.googlesyndication.com/pagead/show_ads.js"}


      #main_content
        .content
          =yield(:breadcrumb)
          = render 'layouts/messages'
          = yield
    #footer
      .col-sm-12
        %br
        %p.text-muted.credit Mexilist
      <a href="https://plus.google.com/102065028150788699450" rel="publisher">Google+</a>


#login_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Registrate
      .modal-body
        .social
          %button.btn.btn-default.btn-lg.facebook
            =image_tag('icons/fb-login.png')
            Conectar con Facebook
        %hr
        %p{:style => "text-align:center"} - Ó por email -
        .email-sign-in
          .well
            =simple_form_for(:user, :url => session_path(:user), :html => {:class => 'form-vertical' }) do |f|
              .row
                .col-sm-12
                  =f.input :email, :autofocus => true
                .col-sm-12
                  =f.input :password, :label => 'Contraseña'

                  -#f.input :remember_me, :as => :boolean, :label => 'recordarme' if devise_mapping.rememberable?
              =link_to '¿Olvidaste tu contraseña?', new_user_password_url
              =f.button :submit, "Ingresar", :class => 'btn-primary pull-right'



        .email-sign-up.well
          =simple_form_for(:user, :url => registration_path(:user), :html => {:class => 'form-vertical' }) do |f|
            =f.error_notification

            =f.input :name, :autofocus => true, :label => 'Nombre'
            =f.input :email, :required => true
            =f.input :password, :required => true, :label => 'Contraseña'
            =f.input :password_confirmation, :required => true, :label => 'Confirmar contraseña'
            =f.button :submit, 'Registrar', :class => 'btn-primary'
      .modal-footer
        %a.btn.btn-warning{:onclick => "$('.email-sign-in').hide();$('.email-sign-up').show();"} Crear Nueva Cuenta